[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "matlab2py-image-analysis"
authors = [{name = "Versatisle", email = "dargaud.laurine@gmail.com"}]
dynamic = ["version", "description"]
